// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEw4gDMEGIP14wI7KBBHtUOQ1bjORE3iU',
    appId: '1:1013797512163:web:0feacc6f1df1c57378f6d6',
    messagingSenderId: '1013797512163',
    projectId: 'jordan-tour-guide',
    authDomain: 'jordan-tour-guide.firebaseapp.com',
    storageBucket: 'jordan-tour-guide.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxawqgY3YbNP9jnuxYZU5SvmRHUQpFFoE',
    appId: '1:1013797512163:android:ee320614fc286a1978f6d6',
    messagingSenderId: '1013797512163',
    projectId: 'jordan-tour-guide',
    storageBucket: 'jordan-tour-guide.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDntQGTIMRE30PaFLmevs60gz0tfGR-26M',
    appId: '1:1013797512163:ios:bb7252a1c0a44cb578f6d6',
    messagingSenderId: '1013797512163',
    projectId: 'jordan-tour-guide',
    storageBucket: 'jordan-tour-guide.appspot.com',
    iosClientId: '1013797512163-g84vikiddu8cfrlhg5t6634nd0ain1e9.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourGuideApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDntQGTIMRE30PaFLmevs60gz0tfGR-26M',
    appId: '1:1013797512163:ios:bb7252a1c0a44cb578f6d6',
    messagingSenderId: '1013797512163',
    projectId: 'jordan-tour-guide',
    storageBucket: 'jordan-tour-guide.appspot.com',
    iosClientId: '1013797512163-g84vikiddu8cfrlhg5t6634nd0ain1e9.apps.googleusercontent.com',
    iosBundleId: 'com.example.tourGuideApp',
  );
}
